Add LLAMA 3.1 Json tool call with Bumblebee
brainlid/langchain pull request #198
Opened 2024-12-01 00:02 UTC by marcnnn

This PR adds the Basic JSON tool calling functionality for LLAMA 3.1

The output is not as stable as I hoped it would be, maybe I need to adjust the template a little.

The tool calling will only be used if you use the template:

```elixir
LangChain.ChatModels.ChatBumblebee.new!(%{
      serving: Llama,
      template_format: :llama_3_1_json_tool_calling,
      stream: false
    })
```

2024-12-02 13:30 UTC, marcnnn commented
In the example, I added:
`Do not mention that you used function calling to the user.`
To the System prompt with that, the output was stable.

@brainlid before merge in the example notebook, we should change that import, if you like everything else so far.

2024-12-03 08:47 UTC, xhr15 commented on README.md
>  Currently, function calling is NOT supported with these models.
Maybe rephrase this to 
"Currently, function calling is only supported for llama 3.1  Tool calling for Llama 2, Mistral, and Zephyr is NOT supported.

2024-12-03 23:42 UTC, brainlid requested changes
It looks like the code formatter could also be run.

Thanks for all this work!

2024-12-03 23:42 UTC, brainlid commented on lib/chat_models/chat_bumblebee.ex
> +    |> IO.inspect
Remove the IO.inspect

2024-12-03 23:43 UTC, brainlid commented
> @brainlid before merge in the example notebook, we should change that import, if you like everything else so far.

Sorry, change what import?

2024-12-04 12:40 UTC, marcnnn commented on notebooks/bumblebee_llama3_1_json_tooluse.livemd
> +    {:langchain, github: "marcnnn/langchain", branch: "llama3_1_json_tool"}
This one should import just the latest version after published.

2024-12-04 13:03 UTC, marcnnn commented
Thanks for the feedback!
Since you saw no big problems with the implementation,
I will continue to look into other tool calling methods and other models.

2025-01-15 04:54 UTC, brainlid reviewed
This is a very meaty change! That's some impressive work. 

My biggest question is about nimble_parsec and needing to resolve the merge conflict. But I think it looks good. 🙂

2025-01-15 04:54 UTC, brainlid commented on lib/chat_models/chat_bumblebee.ex
> +    IO.inspect(content)
Remove the IO.inspect?

2025-01-15 04:54 UTC, brainlid commented on lib/chat_models/chat_bumblebee.ex
> +      values: [:inst, :im_start, :zephyr, :llama_2, :llama_3, :llama_3_1_json_tool_calling, :llama_3_1_custom_tool_calling, :llama_3_2_custom_tool_calling]
This is the line where I think the merge conflict is. It should be a very simple fix though.

2025-01-15 04:54 UTC, brainlid commented on lib/utils/chat_templates.ex
> +        IO.inspect(param_config)
IO.inspect to remove

2025-01-15 04:54 UTC, brainlid commented on lib/utils/chat_templates.ex
> +  Environment: ipython
The `ipython` bit surprises me a bit! I'm sure it makes sense somehow. :)

2025-01-15 04:54 UTC, brainlid commented on lib/utils/parser/llama3_2_custom_tool_paser.ex
> +  import NimbleParsec
I noticed this PR adds the nimble_parsec dependency and it uses the "defparsec" macro.

Can you explain a bit more about what it's help to solve? I'm careful to not add dependencies that aren't needed, or it could be solved in a way that didn't require the dep.

2025-01-15 04:54 UTC, brainlid commented on notebooks/bumblebee_llama3_1_json_tooluse.livemd
> +    {:langchain, github: "marcnnn/langchain", branch: "llama3_1_json_tool"}
Ah, yes. I get what you mean.

2025-01-15 12:17 UTC, marcnnn commented on lib/utils/parser/llama3_2_custom_tool_paser.ex
> +  import NimbleParsec
The Tool call output of Llama3.2 is not just JSON.
It is a python like list of function calls.

Using parsec makes reading, understanding and changing much easier than self written parser code.
Since many Security Problems in Programming are in parser Code, I decided to use a parser generator when ever possible.
And I am used to writing context free grammar, it is the natural why to solve parsing.

If an argument can be a key value Map / dictionary / (JSON/Python) Object or a List, then I would think it's harder to understand without a parser generator.
But I have not found documentation on Llama3.2 support for that.
If someone is interested, let my know or test it out and let me know.

@brainlid Is there an easy way to parse that without dependencies?

2025-01-15 13:28 UTC, brainlid commented on lib/utils/parser/llama3_2_custom_tool_paser.ex
> +  import NimbleParsec
@marcnnn,

Perhaps the best option is to make the dependency optional and check that it's available in the Bumblebee-related code. It could even error if not present and tell them the dependency is needed.

Like this: 
```elixir
{:nimble_parsec, "~> 1.4", optional: true}
```

Then when using it:

```elixir
  if Code.ensure_loaded?(NimbleParsec) do
    # ... use the code ...
  else
    # raise error that optional dependency is required
  end
```

Also, is there a specific LLaMa version that is required for this to work? Is it a fine-tuned derivative model? Is is the stock model available from Meta? 

The docs should probably include a link to a version of the model that this is designed to work with.

2025-01-15 14:16 UTC, marcnnn commented on lib/utils/chat_templates.ex
> +  Environment: ipython
https://www.llama.com/docs/model-cards-and-prompt-formats/llama3_1
Under the topic:

User-defined Custom tool calling

This is what Meta trained with.

2025-01-15 14:51 UTC, marcnnn commented on lib/utils/parser/llama3_2_custom_tool_paser.ex
> +  import NimbleParsec
It works with Meta Llama 3.[1-3] instruction-turned models:

https://www.llama.com/docs/model-cards-and-prompt-formats/llama3_1

https://www.llama.com/docs/model-cards-and-prompt-formats/llama3_2

https://www.llama.com/docs/model-cards-and-prompt-formats/llama3_3

I can do that and check only on the templates that need parsec...

I would do the `Code.ensure_loaded?(NimbleParsec)` before the LLM is called for the User to fail fast, even if this means that the code is not close together?

Llama 3.3 was not tested since it is too big for one GPU and distribution is currently worked on by Paulo.

I could add my Livebooks as examples in a separate PR to not add too much at once?

2025-01-15 15:06 UTC, brainlid commented on lib/utils/parser/llama3_2_custom_tool_paser.ex
> +  import NimbleParsec
Thanks for the links! We can include those in the docs as a resource.

As for the `Code.ensure_loaded?` check, I lean towards keeping it in the custom tool parser usage. The reason is, I might validly use Llama 3 without any intention of using tool calls. 

Also, hitting the issue will happen during development time as the developer tries to use that feature. That feels like a fine time and developer experience to me. 

> Llama 3.3 was not tested since it is too big for one GPU and distribution is currently worked on by Paulo.

That makes sense. Don't worry about that. :slightly_smiling_face:

2025-01-21 11:49 UTC, marcnnn commented on lib/utils/parser/llama3_2_custom_tool_paser.ex
> +  import NimbleParsec
Parsec is Optional now and is only needed for custom tool calling.

2025-01-22 19:07 UTC, brainlid commented
@marcnnn, I'm not sure if this is ready yet. Just let me know when you're happy with where it is. :slightly_smiling_face:

2025-01-22 19:13 UTC, marcnnn commented
I would say I am ready

2025-01-22 19:55 UTC, merged

2025-01-22 19:55 UTC, brainlid commented
Awesome @marcnnn!

Thanks for working through all that and bringing this great enhancement.
❤️💛💙💜